### PR TITLE
Packaging and Improvements

### PR DESCRIPTION
**Pull request by cpmachado**
Hello there mate,

Thought of giving you a present.

Packaged the methods, renamed, and restructured to a more serious looking repo.

The goal was to give you a reference.

I leave you with an exercise: Add pytest coverage.

Used:
- testing: pytest
- lint: flake8
- automation: tox
- packaging: setuptools

Don't forget, Squash merge it, as a feature of a name of your liking, and don't just merge it. :-)

### CODE REVIEW

**Comment by cpmachado** [comment]
Another exercise: Add Github actions CI/CD to test on push

**Review by cpmachado — COMMENTED** [review]
I recommend using https://www.toptal.com/developers/gitignore/ for gitignores
It really covers 99% of what you need

**Review by cpmachado — COMMENTED** [review]
VS Code, and others have plugins to support this, so that everyone is on page.

You can read more on https://editorconfig.org/

**Review by cpmachado — COMMENTED** [review]
The names were long, and one of them didn't have the .py extension

**Review by cpmachado — COMMENTED** [review]
As typing is a non functional part of the code, sometimes it slips in IDE's or envs with from typing import * 

It's excused to say, that it should always have the correct imports.

**Review by cpmachado — COMMENTED** [review]
Generic basic test, I think you can do a better job than me testing your code functionally.

This is the part in which I ramble about functional programming, and about not having side effects.

In both functions, they change the arrays, which might be undesirable.

**Review by cpmachado — COMMENTED** [review]
Your generic pyproject.toml

This is a good official tutorial: https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Review by cpmachado — COMMENTED** [review]
I like to use either tox or nox as a task runner there are others.

tox website: https://tox.wiki/en/latest/

I have a preference for pytest and it is the most commonly used.

pytest website: https://docs.pytest.org/en/7.1.x/

**Review by cpmachado — COMMENTED** [review]
Normally I use pylint, but wanted to try something different.

I'm still looking into flake8.
A lot of people prefer it as a linter, I recommend looking into it

flake8 website: https://flake8.pycqa.org/en/latest/

**Comment by cpmachado** [comment]
@marcelohcortez when are you merging this?

**Comment by marcelohcortez** [comment]
@cpmachado done.

**Pull request merged**
